import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { API_KEY_ENV, MODELS_URL, REQUEST_TIMEOUT_MS } from "../src/config.js";
import { parseModelCatalog } from "../src/novita-api.js";

// Keep this list aligned with Novita's recommended-model guide.
const FALLBACK_MODEL_IDS = [
  "moonshotai/kimi-k2.7-code",
  "zai-org/glm-5.2",
  "deepseek/deepseek-v4-pro",
  "deepseek/deepseek-v3.2",
  "qwen/qwen3.5-397b-a17b",
  "minimax/minimax-m3",
  "deepseek/deepseek-v4-flash",
  "moonshotai/kimi-k2.5",
  "google/gemma-4-31b-it",
  "inclusionai/ling-2.6-flash",
  "meta-llama/llama-3.1-8b-instruct",
  "google/gemma-4-26b-a4b-it",
] as const;

const headers: Record<string, string> = { Accept: "application/json" };
const apiKey = process.env[API_KEY_ENV];
if (apiKey) headers.Authorization = `Bearer ${apiKey}`;

const response = await fetch(MODELS_URL, {
  headers,
  signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
});
if (!response.ok) throw new Error(`/v1/models returned HTTP ${response.status}`);

const parsed = parseModelCatalog((await response.json()) as unknown);
if (!parsed) throw new Error("Novita returned an invalid model catalog");
const byId = new Map(parsed.models.map((model) => [model.id, model]));
const missing = FALLBACK_MODEL_IDS.filter((id) => !byId.has(id));
if (missing.length > 0) {
  throw new Error(`Fallback model ids are no longer available: ${missing.join(", ")}`);
}
const models = FALLBACK_MODEL_IDS.map((id) => byId.get(id)!);
const refreshedOn = new Date().toISOString().slice(0, 10);
const output = `import type { NovitaModel } from "./novita-api.js";\n\n` +
  `export const FALLBACK_SOURCE_URL = ${JSON.stringify(MODELS_URL)};\n` +
  `export const FALLBACK_REFRESHED_ON = ${JSON.stringify(refreshedOn)};\n\n` +
  `// Generated by npm run catalog:refresh from the validated live catalog.\n` +
  `export const FALLBACK_MODELS: NovitaModel[] = ${JSON.stringify(models, null, 2)};\n`;

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
await writeFile(resolve(root, "src", "fallback-models.ts"), output, "utf8");
console.log(`Wrote ${models.length} fallback models refreshed on ${refreshedOn}`);
